# Gradient Boosting Classifier

In [ ]:
# Import libraries
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [3]:
# Load data
iris = load_iris()
X = iris.data
y = iris.target

# Optional: Display as DataFrame
df = pd.DataFrame(X, columns=iris.feature_names)
df["target"] = y

# Train/test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [4]:
# Initialize Gradient Boosting Classifier
gbc = GradientBoostingClassifier(
    n_estimators=100,    # number of boosting stages
    learning_rate=0.1,   # shrinkage factor
    max_depth=3,         # depth of each tree
    random_state=42
)

# Train the model
gbc.fit(X_train, y_train)

# Predict on test set
y_pred = gbc.predict(X_test)

In [5]:
# Evaluate
accuracy = accuracy_score(y_test, y_pred)
print(f"\nAccuracy: {accuracy:.2f}")

print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=iris.target_names))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))


Accuracy: 0.97

Classification Report:
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      0.90      0.95        10
   virginica       0.91      1.00      0.95        10

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30


Confusion Matrix:
[[10  0  0]
 [ 0  9  1]
 [ 0  0 10]]


In [6]:
# Predict on a new observation
sample = np.array([[5.1, 3.5, 1.4, 0.2]])
prediction = gbc.predict(sample)
predicted_class = iris.target_names[prediction[0]]
print(f"\nPredicted class for sample: {predicted_class}")



Predicted class for sample: setosa
