# Logistic Regression for Classification

In [ ]:
# Import libraries
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [4]:
# Load data
iris = load_iris()
X = iris.data            # Features (4 numeric columns)
y = iris.target          # Labels (0,1,2 corresponding to species)

# Optional: View as DataFrame
df = pd.DataFrame(X, columns=iris.feature_names)
df["target"] = y

# Train/test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [5]:
# Initialize Logistic Regression
# 'multinomial' for multiclass, 'lbfgs' solver handles it
lr = LogisticRegression(
    multi_class="multinomial",
    solver="lbfgs",
    max_iter=500,    # Increase iterations to ensure convergence
    random_state=42
)

# Train the model
lr.fit(X_train, y_train)

# Predict on test set
y_pred = lr.predict(X_test)

y_pred

/home/maver02/.cache/pypoetry/virtualenvs/7-machinelearninglibraries-HMhgkURg-py3.11/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(


array([0, 2, 1, 1, 0, 1, 0, 0, 2, 1, 2, 2, 2, 1, 0, 0, 0, 1, 1, 2, 0, 2,
       1, 2, 2, 2, 1, 0, 2, 0])

In [ ]:
# Evaluate
accuracy = accuracy_score(y_test, y_pred)
print(f"\nAccuracy: {accuracy:.2f}")

print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=iris.target_names))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))


Accuracy: 0.97

Classification Report:
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      0.90      0.95        10
   virginica       0.91      1.00      0.95        10

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30


Confusion Matrix:
[[10  0  0]
 [ 0  9  1]
 [ 0  0 10]]


In [7]:
# Predict on a new observation
sample = np.array([[5.1, 3.5, 1.4, 0.2]])
prediction = lr.predict(sample)
predicted_class = iris.target_names[prediction[0]]
print(f"\nPredicted class for sample: {predicted_class}")


Predicted class for sample: setosa
