In [2]:
import pandas as pd, numpy as np

In [1]:
# Sample data
data = {
    "age": [25, 32, None, 51.0, 62],
    "salary": [50000, 60000, 80000, None, 120000],
    "department": ["sales", "engineering", "engineering", "hr", ""],
    "satisfied": [1, 0, 0, 1, 1],
}
data

{'age': [25, 32, None, 51.0, 62],
 'salary': [50000, 60000, 80000, None, 120000],
 'department': ['sales', 'engineering', 'engineering', 'hr', ''],
 'satisfied': [1, 0, 0, 1, 1]}

In [5]:
df = pd.DataFrame(data)
df

age    salary   department  satisfied
0  25.0   50000.0        sales          1
1  32.0   60000.0  engineering          0
2   NaN   80000.0  engineering          0
3  51.0       NaN           hr          1
4  62.0  120000.0                       1

In [43]:
df_clean = df.copy()
# Fill empty values
df_clean.department = df_clean["department"].replace("", np.nan)
df_clean

age    salary   department  satisfied
0  25.0   50000.0        sales          1
1  32.0   60000.0  engineering          0
2   NaN   80000.0  engineering          0
3  51.0       NaN           hr          1
4  62.0  120000.0          NaN          1

In [44]:
df_clean.age = df_clean.age.astype('float')
df_clean

age    salary   department  satisfied
0  25.0   50000.0        sales          1
1  32.0   60000.0  engineering          0
2   NaN   80000.0  engineering          0
3  51.0       NaN           hr          1
4  62.0  120000.0          NaN          1

In [45]:
# inputer of numeric columns
numeric_columns = ["age", "salary"]
from sklearn.impute import SimpleImputer
imputer = SimpleImputer()

imputer.fit(df_clean[numeric_columns])
df_clean[numeric_columns] = imputer.transform(df_clean[numeric_columns])
df_clean

age    salary   department  satisfied
0  25.0   50000.0        sales          1
1  32.0   60000.0  engineering          0
2  42.5   80000.0  engineering          0
3  51.0   77500.0           hr          1
4  62.0  120000.0          NaN          1

In [51]:
# encoder of categorical columns
categorical_columns = ["department"]
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(handle_unknown='ignore')
df_clean[categorical_columns] = encoder.fit_transform(df_clean[categorical_columns])

In [52]:
df_clean

age    salary                                         department  \
0  25.0   50000.0  <Compressed Sparse Row sparse matrix of dtype ...   
1  32.0   60000.0  <Compressed Sparse Row sparse matrix of dtype ...   
2  42.5   80000.0  <Compressed Sparse Row sparse matrix of dtype ...   
3  51.0   77500.0  <Compressed Sparse Row sparse matrix of dtype ...   
4  62.0  120000.0  <Compressed Sparse Row sparse matrix of dtype ...   

   satisfied  
0          1  
1          0  
2          0  
3          1  
4          1

In [82]:
import numpy as np
import pandas as pd

# Example data
data = pd.DataFrame({
    "Color": ["red", "blue", "green", "blue", "red", "green"],
    "Size": ["S", "M", "L", "S", "M", "L"],
    "Weight": [10, 15, 20, 12, 18, 22],
    "Target": [0, 1, 0, 1, 0, 1]
})

X = data[["Color", "Size", "Weight"]]
y = data["Target"]

from sklearn.preprocessing import OneHotEncoder

# Select categorical columns
categorical = X[["Color", "Size"]]

# Initialize encoder
encoder = OneHotEncoder()

# Fit and transform
encoded_categorical = encoder.fit_transform(categorical)

print("Encoded feature names:", encoder.get_feature_names_out(["Color", "Size"]))
print("Encoded array:\n", encoded_categorical)


Encoded feature names: ['Color_blue' 'Color_green' 'Color_red' 'Size_L' 'Size_M' 'Size_S']
Encoded array:
 <Compressed Sparse Row sparse matrix of dtype 'float64'
	with 12 stored elements and shape (6, 6)>
  Coords	Values
  (0, 2)	1.0
  (0, 5)	1.0
  (1, 0)	1.0
  (1, 4)	1.0
  (2, 1)	1.0
  (2, 3)	1.0
  (3, 0)	1.0
  (3, 5)	1.0
  (4, 2)	1.0
  (4, 4)	1.0
  (5, 1)	1.0
  (5, 3)	1.0


In [83]:
encoded_categorical = encoded_categorical.toarray()

In [84]:
# Select numeric columns
numeric = X[["Weight"]].to_numpy()

numeric


array([[10],
       [15],
       [20],
       [12],
       [18],
       [22]])

In [85]:
# Concatenate encoded categorical and numeric columns
X_final = np.hstack([encoded_categorical, numeric])

print("Final feature matrix:\n", X_final)

Final feature matrix:
 [[ 0.  0.  1.  0.  0.  1. 10.]
 [ 1.  0.  0.  0.  1.  0. 15.]
 [ 0.  1.  0.  1.  0.  0. 20.]
 [ 1.  0.  0.  0.  0.  1. 12.]
 [ 0.  0.  1.  0.  1.  0. 18.]
 [ 0.  1.  0.  1.  0.  0. 22.]]


In [91]:
X = X_final[:,:-1]
y = X_final[:, -1]

In [92]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [96]:
X_train

array([[0., 1., 0., 1., 0., 0.],
       [0., 1., 0., 1., 0., 0.],
       [0., 0., 1., 0., 1., 0.],
       [1., 0., 0., 0., 0., 1.]])

In [97]:
X_test

array([[0., 0., 1., 0., 0., 1.],
       [1., 0., 0., 0., 1., 0.]])

In [99]:
y_train

array([22., 20., 18., 12.])

In [100]:
y_test

array([10., 15.])

In [101]:
from sklearn.linear_model import LogisticRegression

# Initialize the model
model = LogisticRegression()

# Fit
model.fit(X_train, y_train)


LogisticRegression()

In [102]:
model.predict(X_train)

array([20., 20., 18., 12.])

In [103]:
y_train

array([22., 20., 18., 12.])

In [104]:
model.predict(X_test)

array([12., 12.])

In [105]:
y_test

array([10., 15.])